name: Build Android
on: 
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
    - uses: actions/setup-java@v3
      with: { java-version: '17' }
    - run: npm ci
    - uses: android-actions/setup-android@v2
    - run: npm run build:android
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASS: ${{ secrets.SIGNING_PASS }}
    - uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
    - uses: softprops/action-gh-release@v1
      with:
        files: android/app/build/outputs/apk/release/app-release.apk
