name: Build Android
on: 
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Setup Bun
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - uses: actions/setup-java@v3
      with: { java-version: '17' }
    
    - run: bun install  # Replaces npm ci
    
    - name: Setup Android
      uses: android-actions/setup-android@v2
      
    - name: Build APK
      run: bun run build:android
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASS: ${{ secrets.SIGNING_PASS }}
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Attach to Release
      uses: softprops/action-gh-release@v1
      with:
        files: android/app/build/outputs/apk/release/app-release.apk
