name: Deploy Web
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # 1. Use Node.js 16 (compatible with Expo)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Node 16 works with legacy expo-cli
        
    # 2. Install Bun
    - name: Install Bun
      run: |
        npm install -g bun
        bun -v
        
    # 3. Install dependencies
    - name: Install dependencies
      run: |
        bun install
        npm install -g expo-cli@legacy  # Install legacy CLI explicitly
        
    # 4. Build web app directly (no baseUrl config needed)
    - name: Build web app
      run: |
        # Set base URL in app.json instead
        echo '{"expo": {"web": {"build": {"baseUrl": "/UpliftED-NWU-Student-Support-Ecosystem/"}}}}' > app.json
        expo build:web
        
    # 5. Verify build output
    - name: Verify build
      run: |
        ls -la web-build
        echo "Base URL set to: $(grep baseUrl app.json)"
        
    # 6. Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-build
