name: Deploy Web
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with: { bun-version: 'latest' }
    - run: bun install
    - name: Install Expo CLI
      run: bun add -g expo-cli
    - run: |
        expo config set web.baseUrl /UpliftED-NWU-Student-Support-Ecosystem/
        bun run build:web
    - name: Prepare Deployment
      run: |
        touch web-build/.nojekyll
        echo 'neoknkidi7.github.io/UpliftED-NWU-Student-Support-Ecosystem' > web-build/CNAME
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-build
