name: Deploy Web
on: 
  push:
    branches: [main]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with: { node-version: 18 }
    - run: npm ci
    - run: npm run build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        # Add these lines for client-side routing:
        enable_jekyll: true
        cname: neoknkidi7.github.io/uplifted-nwu-student-support-ecosystem
